#
# Copyright (c) 2011 The Chromium OS Authors.
# SPDX-License-Identifier:	GPL-2.0+
#

# new USB host ethernet layer dependencies
obj-$(CONFIG_MINI2440_USB_SLAVE) += usbin.o  usblib.o \
	usbmain.o  usbout.o  usbsetup.o usbinit.o interrupt.o
